pipeline:
  name: delegate_build
  identifier: delegate_build
  projectIdentifier: RN_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: delegate
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Delegate Type
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |
                      case <+pipeline.variables.delegate_type> in

                        "full_rhel")
                          export del_docker_file="./Dockerfile"
                          ;;

                        "full_ubuntu")
                          export del_docker_file="./Dockerfile-ubuntu"
                          ;;

                        "minimal")
                          export del_docker_file="./Dockerfile-minimal"
                          ;;
                      esac
                    outputVariables:
                      - name: del_docker_file
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to DockerHub
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: rndockerhub
                    repo: delegate
                    tags:
                      - <+pipeline.variables.delegate_type>-
                    dockerfile: <+pipeline.stages.Build.spec.execution.steps.Run_1.output.outputVariables.del_docker_file>
  variables:
    - name: delegate_type
      type: String
      default: full_rhel
      description: ""
      value: <+input>.allowedValues(full_rhel,full_ubuntu,minimal)
